# Generated by Django 4.1.7 on 2023-03-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='Cliente',
            new_name='cliente',
        ),
    ]
